### ISSUE TITLE
Add Celo Ledger support to Web3Modal

### ISSUE THREAD

**Issue by kyscott18** [mobiusAMM/mobius-interface#217]
**Is your feature request related to a problem? Please describe.**
Web3modal doesn't have native support for Celo Ledger. We need to add a custom provider type that allows for connection to ledger using the celo derivation path.

**Describe the solution you'd like**
I would like to add Celo Ledger as a custom type to the web3modal. This makes it look very clean for the interface and also will be better for compatibility going forward.

**Describe alternatives you've considered**
Deprecating Celo ledger is not really an option because a lot of users, including myself, use this feature.

**Comment by d-mooers** [comment]
If we want to add ledger to the web3 modal package, we will need to make a new package for Celo Ledger Modal.

Celo Ledger Modal class:
    - On construction:
        - Attach modal for selecting index to the DOM
        - Listen for "ledger-index" events
        - On a "ledger-index" event, update the ledger index within the wrapper class
    - On enable()
        - Use recorded ledger index to create a new Ledger Connector 
        - Return the raw provider from the Ledger Connector
